In [4]:
#Exp no.:4

In [5]:
#Aim:To perform missing value treatment

In [6]:
#Name:Pranita Sakarde
#Roll no.:51
#Sec:c
#Subject:DSS

In [7]:
#importing the basic library
import pandas as pd

In [8]:
import os

In [9]:
os.getcwd()

'C:\\Users\\USER'

In [10]:
os.chdir("C:\\Users\\USER\\OneDrive\\Desktop")

In [11]:
data=pd.read_csv("heart.csv")

In [12]:
data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [13]:
data.head(51)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
5,57,1,0,140,192,0,1,148,0,0.4,1,0,1,1
6,56,0,1,140,294,0,0,153,0,1.3,1,0,2,1
7,44,1,1,120,263,0,1,173,0,0.0,2,0,3,1
8,52,1,2,172,199,1,1,162,0,0.5,2,0,3,1
9,57,1,2,150,168,0,1,174,0,1.6,2,0,2,1
10,54,1,0,140,239,0,1,160,0,1.2,2,0,2,1
11,48,0,2,130,275,0,1,139,0,0.2,2,0,2,1
12,49,1,1,130,266,0,1,171,0,0.6,2,0,2,1
13,64,1,3,110,211,0,0,144,1,1.8,1,0,2,1
14,58,0,3,150,283,1,0,162,0,1.0,2,0,2,1
15,50,0,2,120,219,0,1,158,0,1.6,1,0,2,1
16,58,0,2,120,340,0,1,172,0,0.0,2,0,2,1
17,66,0,3,150,226,0,1,114,0,2.6,0,0,2,1
18,43,1,0,150,247,0,1,171,0,1.5,2,0,2,1
19,69,0,3,140,239,0,1,151,0,1.8,2,2,2,1
20,59,1,0,135,234,0,1,161,0,0.5,1,0,3,1
21,44,1,2,130,233,0,1,179,1,0.4,2,0,2,1
22,42,1,0,140,226,0,1,178,0,0.0,2,0,2,1
23,61,1,2,150,243,1,1,137,1,1.0,1,0,2,1
24,40,1,3,140,199,0,1,178,1,1.4,2,0,3,1
25,71,0,1,160,302,0,1,162,0,0.4,2,2,2,1
26,59,1,2,150,212,1,1,157,0,1.6,2,0,2,1
27,51,1,2,110,175,0,1,123,0,0.6,2,0,2,1
28,65,0,2,140,417,1,0,157,0,0.8,2,1,2,1
29,53,1,2,130,197,1,0,152,0,1.2,0,0,2,1
30,41,0,1,105,198,0,1,168,0,0.0,2,1,2,1
31,65,1,0,120,177,0,1,140,0,0.4,2,0,3,1
32,44,1,1,130,219,0,0,188,0,0.0,2,0,2,1
33,54,1,2,125,273,0,0,152,0,0.5,0,1,2,1
34,51,1,3,125,213,0,0,125,1,1.4,2,1,2,1
35,46,0,2,142,177,0,0,160,1,1.4,0,0,2,1
36,54,0,2,135,304,1,1,170,0,0.0,2,0,2,1
37,54,1,2,150,232,0,0,165,0,1.6,2,0,3,1
38,65,0,2,155,269,0,1,148,0,0.8,2,0,2,1
39,65,0,2,160,360,0,0,151,0,0.8,2,0,2,1
40,51,0,2,140,308,0,0,142,0,1.5,2,1,2,1
41,48,1,1,130,245,0,0,180,0,0.2,1,0,2,1
42,45,1,0,104,208,0,0,148,1,3.0,1,0,2,1
43,53,0,0,130,264,0,0,143,0,0.4,1,0,2,1
44,39,1,2,140,321,0,0,182,0,0.0,2,0,2,1
45,52,1,1,120,325,0,1,172,0,0.2,2,0,2,1
46,44,1,2,140,235,0,0,180,0,0.0,2,0,2,1
47,47,1,2,138,257,0,0,156,0,0.0,2,0,2,1
48,53,0,2,128,216,0,0,115,0,0.0,2,0,0,1
49,53,0,0,138,234,0,0,160,0,0.0,2,0,2,1
50,51,0,2,130,256,0,0,149,0,0.5,2,0,2,1

In [14]:
data.tail()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [15]:
age=data[data["age"]>60]

In [16]:
print(age)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3
13    64    1   3       110   211    0        0      144      1      1.8
17    66    0   3       150   226    0        1      114      0      2.6
19    69    0   3       140   239    0        1      151      0      1.8
23    61    1   2       150   243    1        1      137      1      1.0
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
290   61    1   0       148   203    0        1      161      0      0.0
293   67    1   2       152   212    0        0      150      0      0.8
295   63    1   0       140   187    0        0      144      1      4.0
296   63    0   0       124   197    0        1      136      1      0.0
300   68    1   0       144   193    1        1      141      0      3.4

     slope  ca  thal  target
0        0   0     1       1
13       1   0     2       1
17       0   0     2       1
19       2   2     2       1
23       1   0     2       1
..     ...  ..   ...     ...
290      2   1     3       0
293      1   0     3       0
295      2   2     3       0
296      1   0     2       0
300      1   2     3       0

[79 rows x 14 columns]

missing value

In [17]:
data.isna()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,False,False,False,False,False,False,False,False,False,False,False,False,False,False
299,False,False,False,False,False,False,False,False,False,False,False,False,False,False
300,False,False,False,False,False,False,False,False,False,False,False,False,False,False
301,False,False,False,False,False,False,False,False,False,False,False,False,False,False
302,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [18]:
data.isna().any()

age         False
sex         False
cp          False
trestbps    False
chol        False
fbs         False
restecg     False
thalach     False
exang       False
oldpeak     False
slope       False
ca          False
thal        False
target      False
dtype: bool

In [19]:
data.sum()

age         16473.0
sex           207.0
cp            293.0
trestbps    39882.0
chol        74618.0
fbs            45.0
restecg       160.0
thalach     45343.0
exang          99.0
oldpeak       315.0
slope         424.0
ca            221.0
thal          701.0
target        165.0
dtype: float64

In [20]:
data.dropna()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [21]:
data.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [22]:
#Method for missing value treatment

In [23]:
df2=data["age"].fillna(30.272590)

In [24]:
df2.isna().sum()

np.int64(0)

In [25]:
#method 2

In [26]:
df1=data.fillna(data.mean())

In [27]:
data.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [28]:
df2.isna().sum()

np.int64(0)