In [18]:
#Exp no.:6

In [19]:
#Aim:To perform a opeartion of sampling and population

In [1]:
#Name:Pranita Sakarde
#Roll no.:51
#Sec:c
#Subject:DSS

In [21]:
#importing the basic library
import pandas as pd

In [22]:
import os

In [23]:
os.getcwd()

'C:\\Users\\USER\\OneDrive\\Desktop'

In [24]:
os.chdir("C:\\Users\\USER\\OneDrive\\Desktop")

In [25]:
data=pd.read_csv("heart.csv")

In [26]:
data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [27]:
data.tail()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [34]:
data.shape

(303, 14)

In [35]:
data.size

4242

In [37]:
data.ndim

2

In [38]:
data.isna()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,False,False,False,False,False,False,False,False,False,False,False,False,False,False
299,False,False,False,False,False,False,False,False,False,False,False,False,False,False
300,False,False,False,False,False,False,False,False,False,False,False,False,False,False
301,False,False,False,False,False,False,False,False,False,False,False,False,False,False
302,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [39]:
data.isna().any()

age         False
sex         False
cp          False
trestbps    False
chol        False
fbs         False
restecg     False
thalach     False
exang       False
oldpeak     False
slope       False
ca          False
thal        False
target      False
dtype: bool

In [40]:
data.sum()

age         16473.0
sex           207.0
cp            293.0
trestbps    39882.0
chol        74618.0
fbs            45.0
restecg       160.0
thalach     45343.0
exang          99.0
oldpeak       315.0
slope         424.0
ca            221.0
thal          701.0
target        165.0
dtype: float64

In [44]:
age_above_60=data[data["age"]>60]
print(age)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3
13    64    1   3       110   211    0        0      144      1      1.8
17    66    0   3       150   226    0        1      114      0      2.6
19    69    0   3       140   239    0        1      151      0      1.8
23    61    1   2       150   243    1        1      137      1      1.0
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
290   61    1   0       148   203    0        1      161      0      0.0
293   67    1   2       152   212    0        0      150      0      0.8
295   63    1   0       140   187    0        0      144      1      4.0
296   63    0   0       124   197    0        1      136      1      0.0
300   68    1   0       144   193    1        1      141      0      3.4

     slope  ca  thal  target
0        0   0     1       1
13       1   0     2       1
17       0   0     2       1
19       2   2     2       1
23       1   0     2       1
..     ...  ..   ...     ...
290      2   1     3       0
293      1   0     3       0
295      2   2     3       0
296      1   0     2       0
300      1   2     3       0

[79 rows x 14 columns]

In [45]:
print(len(age_above_60))

79

In [46]:
chol_above_250=data[data["chol"]>250]
print(chol_above_250)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
4     57    0   0       120   354    0        1      163      1      0.6
6     56    0   1       140   294    0        0      153      0      1.3
7     44    1   1       120   263    0        1      173      0      0.0
11    48    0   2       130   275    0        1      139      0      0.2
12    49    1   1       130   266    0        1      171      0      0.6
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
280   42    1   0       136   315    0        1      125      1      1.8
285   46    1   0       140   311    0        1      120      1      1.8
288   57    1   0       110   335    0        1      143      1      3.0
291   58    1   0       114   318    0        2      140      0      4.4
299   45    1   3       110   264    0        1      132      0      1.2

     slope  ca  thal  target
4        2   0     2       1
6        1   0     2       1
7        2   0     3       1
11       2   0     2       1
12       2   0     2       1
..     ...  ..   ...     ...
280      1   0     1       0
285      1   2     3       0
288      1   1     3       0
291      0   3     1       0
299      1   0     3       0

[126 rows x 14 columns]